config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'authors#index'
  resources :authors
  get "authors", to: "authors#index"

end

app/models/application_record.rb
class Author < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Authors < ApplicationRecord
  

 has_many :books, dependent: :destroy


end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :Author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    def index
        @authors = Author.all    
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<h1>All the Artists</h1>


<table class="striped bordered">
  <tr>
    <th>Artist</th>
    <th>Image</th>
    <th>Albums</th>
    <th>Hometown</th>
  </tr>

  <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.first_name, author_path(author) %></td>
        <td><%= author.last_name %></td>
        <td><%= author.genre %></td>
        <td><%= author.birthdate %></td>
      </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>